apiVersion: v1
kind: Pod
metadata:
  name: config-service
  labels: 
    app: config-service
    version: v1
spec:
  containers:
  - name: config-service
    image: rauny/config-service:v1
    ports:
    - containerPort: 8888
